### ISSUE TITLE
xbt error on ubuntu 14.4

### ISSUE THREAD

**Issue by Hostile** [Bigjoos/U-232-V4#70]
root@vodeoo:~/xbt/Tracker# ./make.sh
transaction.cpp: In member function ‘void Ctransaction::recv()’:
transaction.cpp:37:15: error: ‘class Cstats’ has no member named ‘received_udp’
   srv_stats().received_udp++;
               ^
transaction.cpp: In member function ‘void Ctransaction::send_announce(data_ref)’:
transaction.cpp:106:33: error: no matching function for call to ‘t_torrent::select_peers(mutable_str_ref&, Ctracker_input&) const’
  torrent->select_peers(peers, ti);
                                 ^
transaction.cpp:106:33: note: candidate is:
In file included from transaction.cpp:5:0:
server.h:93:14: note: std::string t_torrent::select_peers(const Ctracker_input&) const
  std::string select_peers(const Ctracker_input&) const;
              ^
server.h:93:14: note:   candidate expects 1 argument, 2 provided
transaction.cpp: In member function ‘void Ctransaction::send(data_ref)’:
transaction.cpp:156:14: error: ‘class Cstats’ has no member named ‘sent_udp’
  srv_stats().sent_udp++;

**Comment by whocares-openscene** [comment]
This is fixed by commit 425c7df2d428ad42913e4025e96552df29971d79

**Comment by Bigjoos** [comment]
Closed.
